sudo: required
dist: trusty
language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js: lts/*
branches:
  only:
    - master
    - /^greenkeeper/.*$/
stages:
  - test
  - name: deploy
    if: branch = master and type != pull_request
jobs:
  include:
    - stage: test
      script:
        - yarn build
        - yarn ci
        - yarn test:report
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release
